include: package:flutter_lints/flutter.yaml
analyzer:
  strong-mode:
  errors:
    missing_required_param: warning
    undefined_prefixed_name: ignore
    todo: ignore
    deprecated_member_use_from_same_package: ignore
  exclude:
    - "bin/cache/**"
    - "test/**"
    - "test_driver/**"
    - "lib/i18n/messages_*.dart"
    - "lib/src/http/**"

linter:
  rules:
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    unnecessary_parenthesis: true
    non_constant_identifier_names: ignore