name: ones_ai_flutter
description: ones ai Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^0.1.2
  fluintl: ^0.1.3
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  redux_thunk: ^0.3.0

  #shared_preferences: ^0.5.7+1 #offical lib support ios  android web.
  #flutter localstorage for ios/android/desktop/web
  localstorage: ^3.0.2+5
  webview_flutter: ^0.3.21
  url_launcher: ^5.4.5
  bot_toast: ^3.0.0
  rxdart: ^0.24.0
  flustars: ^0.2.5+1
  fluro:
    git:
      url: git://github.com/theyakka/fluro.git
  #网页中唤醒原生app页面
  uni_links: ^0.2.0
  #  fluro: #"^1.5.1"
  auto_size:
    git:
      url: git://github.com/flutterchina/auto_size.git
  connectivity: ^0.4.8+5 #ios android
  dio: ^3.0.9 #all
  dio_http_cache: ^0.2.6 # ios android
  json_serializable: ^3.3.0
  pretty_dio_logger: ^1.1.1
  #https://pub.dev/packages/pull_to_refresh#-readme-tab-
  #pull_to_refresh: ^1.5.7
  flutter_easyrefresh: ^2.1.1 #android ios web
  #https://pub.dev/packages/cached_network_image#-installing-tab-
  cached_network_image: ^2.2.0+1 #ios android
  #https://github.com/zino-app/graphql-flutter
#  graphql_flutter: ^2.0.0 #android ios
  #键盘弹起和隐藏
  keyboard_visibility: ^0.5.6  # android ios web
  retrofit: ^1.3.4
  logger: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  #  json_model: #latest version
  build_runner: any
#  json_serializable: ^3.3.0
  retrofit_generator: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/welcome.png
    - assets/images/default_avatar.png
    - assets/images/ones_icon.png
    - assets/html/css/style.css
    - assets/html/js/function.js
    - assets/html/index.html
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/aliconfont.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
