name: ones-mobile-ci

on:
  push:
    branches:
      - "F[0-9]+"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: []

jobs:
  ios-build-job:
    name: start build iOS
    runs-on: macOS-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: false
      - name: Extract branch or tag name
        id: CURRENT_TAG_OR_TAG
        uses: ypicard/get-branch-name-github-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.21.0-9.1.pre'
          channel: 'beta'
      - name: build iOS with fastlane
        env:
          CURRENT_TAG: ${{ steps.CURRENT_TAG_OR_TAG.outputs.tag }}
          CURRENT_BRANCH: ${{ steps.CURRENT_TAG_OR_TAG.outputs.branch }}
        run: sh ./ios/build.sh